version: '3.4'

services:
  alerting.producer:
    image: ${DOCKER_REGISTRY-}alertingproducer
    build:
      context: .
      dockerfile: Alerting.Producer/Dockerfile
    extra_hosts:
    - "host.docker.internal:host-gateway"

  alerting.consumer:
    image: ${DOCKER_REGISTRY-}alertingconsumer
    build:
      context: .
      dockerfile: Alerting.Consumer/Dockerfile

