version: '3.4'

services:
  alerting.producer:
    image: ${DOCKER_REGISTRY-}alertingproducer
    build:
      context: .
      dockerfile: Alerting.Producer/Dockerfile
    extra_hosts:
    - "host.docker.internal:host-gateway"

  alerting.consumer:
    image: ${DOCKER_REGISTRY-}alertingconsumer
    build:
      context: .
      dockerfile: Alerting.Consumer/Dockerfile


  alerting.controller:
    image: ${DOCKER_REGISTRY-}alertingcontroller
    build:
      context: .
      dockerfile: Alerting.Controller/Dockerfile


  alerting.alerting:
    image: ${DOCKER_REGISTRY-}alertingalerting
    build:
      context: .
      dockerfile: Alerting.Alerting/Dockerfile


  alerting.alertingruleconsumer:
    image: ${DOCKER_REGISTRY-}alertingalertingruleconsumer
    build:
      context: .
      dockerfile: Alerting.AlertingRuleConsumer/Dockerfile

