// <auto-generated />
using System;
using Alerting.Domain.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Alerting.Domain.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221023052553_StateTypesAdded")]
    partial class StateTypesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Alerting.Domain.DataBase.Alerting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChatId")
                        .HasColumnType("text");

                    b.Property<Guid?>("ClientStateId")
                        .HasColumnType("uuid");

                    b.Property<int>("WaitingInterval")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.HasIndex("ClientStateId");

                    b.ToTable("Alertings");
                });

            modelBuilder.Entity("Alerting.Domain.DataBase.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Alerting.Domain.DataBase.ClientState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastAlerted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TypeId");

                    b.ToTable("ClientStates");
                });

            modelBuilder.Entity("Alerting.Domain.DataBase.StateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StateTypes");
                });

            modelBuilder.Entity("Alerting.Domain.DataBase.TelegramBot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TelegramBots");
                });

            modelBuilder.Entity("Alerting.Domain.DataBase.Alerting", b =>
                {
                    b.HasOne("Alerting.Domain.DataBase.TelegramBot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId");

                    b.HasOne("Alerting.Domain.DataBase.ClientState", "ClientState")
                        .WithMany()
                        .HasForeignKey("ClientStateId");
                });

            modelBuilder.Entity("Alerting.Domain.DataBase.ClientState", b =>
                {
                    b.HasOne("Alerting.Domain.DataBase.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("Alerting.Domain.DataBase.StateType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("Alerting.Domain.DataBase.TelegramBot", b =>
                {
                    b.HasOne("Alerting.Domain.DataBase.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");
                });
#pragma warning restore 612, 618
        }
    }
}
